import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "~/components/Header";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: posts } = api.post.getAll.useQuery();
  console.log(posts);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-gray-50">
        <Header />

        {/* Hero section */}
        <div className="my-16 text-center">
          <h1 className="text-8xl font-bold text-gray-800">Blog</h1>
          <Link href="/new">
            <button className="w-48 mt-8 bg-slate-700 text-white py-2 rounded-md hover:bg-slate-600">
              <span className="text-xl mr-2 h-fit leading-none">+</span>
              Write new post
            </button>
          </Link>
        </div>

        {/* Blog posts */}
        <div className="max-w-screen-lg w-full mx-auto mt-12 grid grid-cols-3 gap-5">
          {posts && posts.map(post => (
            <div className="border border-gray-200 shadow-sm rounded-lg p-5 bg-white" key={post.id}>
              <h2 className="font-bold text-xl">{post.title}</h2>
              <p className="mt-3 font-light text-base">{post.content}</p>
              <Link href="/" className="align-middle underline mt-3 block">Read More →</Link>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
